/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class User { 
// Inherited properties
//    public id: number;
//    public name: string;
//    public surname: string;
//    public patronymic: string;
//    public login: string;
//    public passwordHash: string;
//    public createdOn: Date;
//    public phone: string;
//    public email: string;
//}
//export class UserBase { 
//    public id: number;
//    public name: string;
//    public surname: string;
//    public patronymic: string;
//    public login: string;
//    public passwordHash: string;
//    public createdOn: Date;
//    public phone: string;
//    public email: string;
//}*/


export class UserBase {
    public id: number;
    public name: string;
    public surname: string;
    public patronymic: string;
    public login: string;
    public passwordHash: string;
    public createdOn: Date;
    public phone: string;
    public email: string;
}


export class User extends UserBase { 
}
