/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class TokenInfo { 
//    public token: string;
//    public createdOn: Date;
//    public expiresOn: Date;
//    public tokenType: string;
//}
//export class UserLoginModel { 
//    public login: string;
//    public password: string;
//    public email: string;
//}*/

export class TokenInfo {
    public token: string;
    public createdOn: Date;
    public expiresOn: Date;
    public tokenType: string;
}

export class UserLoginModel {
    public login: string;
    public password: string;
    public email: string;
}


